### ISSUE TITLE
Question about Error type

### ISSUE THREAD

**Issue by Chandlercjy** [fxcm/fxcmpy#1]
Hi,

I am glad that finally, FXCM publishes the official Python API.
But I find that there is no documentation for error message.

For example:
ServerError: FXCM Server reports an error: Unauthorized.

I am wondering are there any other Error that will be generated by this API. Such as failing to submit the order and etc. So that I can deal with the errors and try to resend the order.

Thank you!

**Comment by FXCMAPI** [comment]
Hi,

The “Unauthorized“  error means the REST API is not enabled for the username or the token is not valid.
For trading errors, you will see more details.
For a specific case, please email it to api@fxcm.com<mailto:api@fxcm.com>

https://fxcm.github.io/rest-api-docs/#

Regards,
Daniel Halpert

**Comment by FXCMAPI** [comment]
Close it
