### ISSUE TITLE
Subscription to market simply stops.

### ISSUE THREAD

**Issue by JTInfinite** [fxcm/fxcmpy#10]
Hello,

First off, thanks for the nice wrapper to your API. Much appreciated.

I have an issue whereby when I subscribe to various markets I will get 2 to 5 prices before the subscriptions are stopped and my script exits cleanly without instruction. The last line in the logfile is always 'heartbeat reset' (I've copied in the last 3 line of the logfile below).

As you can see from the below I am using a demo account.

What is happening and am I doing something wrong?

|DEBUG|2018-07-11 08:08:51,768|https://api-demo.fxcm.com:443 "GET /socket.io/?access_token='REMOVED'&agent=pythonquants&EIO=3&transport=polling&t=1531292931662-0 HTTP/1.1" 200 101
|DEBUG|2018-07-11 08:08:52,307|api-demo.fxcm.com:443/socket.io [engine.io transport selected] websocket
|DEBUG|2018-07-11 08:08:52,309|api-demo.fxcm.com:443/socket.io [engine.io heartbeat reset]

Thanks

**Comment by FXCMAPI** [comment]
Hi,

Can you please email the token and the function in use with it’s parameters list.
Please email it to api@fxcm.com<mailto:api@fxcm.com>

Regards,
Daniel Halpert

**Comment by JTInfinite** [comment]
Done. Thanks.
