### ISSUE TITLE
why python api get data so different  with MT4 at same time?

### ISSUE THREAD

**Issue by henryatman** [fxcm/fxcmpy#12]
why python api get data so different  with MT4 at same time,

include data time, data price, even tickqty, all is different

python api (fxcmpy) connect to api-demo.fxcm.com

MT4 connect 'FXCM-USDDemo01’,

what does each time mean?
why have this problem ? 

Is demo server just playground  fill with random data ? 

it’s very big problem and bother me, more detail is:

pls help answer, tks

capture software screen at same time in below : 

![image](https://user-images.githubusercontent.com/5210789/43375226-52d909d4-93e6-11e8-82fc-8e676ab6da60.png)
![image](https://user-images.githubusercontent.com/5210789/43375229-5713fbb2-93e6-11e8-80de-b6129720819d.png)

**Comment by FXCMAPI** [comment]
Because of MT4 server limitations, it can’t process all prices we have, this why you may see the difference in price and tick volume.
The REST API historical data should have all prices.

Regards,
Daniel Halpert

**Comment by FXCMAPI** [comment]
Closing it.
