### ISSUE TITLE
what should i do if i want to connect FXCM server use socks5 with password?

### ISSUE THREAD

**Issue by henryatman** [fxcm/fxcmpy#13]
what should i do if i want to connect FXCM server use socks5 with password?

i saw the doc http://fxcmpy.tpq.io/01_connecting.html say API can use proxy to connect,

but doc not say how to set password and encryption method if i use socks5 proxy,

is there any way to do this ?

**Comment by FXCMAPI** [comment]
Hi,

Can you try adding username and password to proxy_url in fxcmpy constructor ?
For example:
con = fxcmpy.fxcmpy(access_token='TOKEN', proxy_type='socks5', proxy_url='username:password@example.com', proxy_port=1234)
I am unable to test this at the moment but I believe it should work.
Thank you.

Best Regards,
Pawel

**Comment by henryatman** [comment]
@FXCMAPI 

too sad, it's seem don't work after i try, because socks5 protocol connect format not even have username?

socks5 protocol only have two Param:
1.  "method" like (Your Encryption Method:  aes-256-cfb) 
2. "password" (xxx) except for port

are you sure con = fxcmpy.fxcmpy(access_token='TOKEN', proxy_type='socks5', proxy_url='username:password@example.com', proxy_port=1234) it's work?

or can you confirm this way and is there have any other way ?

need you help! thanks

**Comment by FXCMAPI** [comment]
I have tested this method with custom 3proxy server and was able to connect properly using this command:
con = fxcmpy.fxcmpy(access_token="...", proxy_type='socks5', proxy_url='test:test@localhost', proxy_port=1080)
As far as I can tell, if SOCKS5 requires password it will also require a username.
I was unable to find any information on password-only SOCKS5 and could not find any information on how to configure 3proxy to require only password.

**Comment by henryatman** [comment]
@FXCMAPI 
very thanks for your patience help, it's wrong by me, i tell only  have password it's socks5 server backend, socks5 still need install client to connect socks5 server, then other software need to connect socks5 local client rather than straight connect socks5 server, it's totally my understand wrong.

But... there have another question stuck me now, i use the `get_candles` to get forex `m1` data,

2018-08-07 23:48:00,0.99528,0.99526,0.99533,0.99526,0.99545,0.99543,0.99549,0.99541,58
2018-08-07 23:49:00,0.99526,0.99525,0.99527,0.9952,0.99543,0.99541,0.99544,0.99533,47
2018-08-07 23:51:00,0.99525,0.99525,0.99526,0.99525,0.99541,0.99541,0.99541,0.99541,2
2018-08-07 23:52:00,0.99525,0.99524,0.99526,0.99524,0.99541,0.9954,0.99541,0.9954,6
2018-08-07 23:53:00,0.99524,0.99519,0.99526,0.99518,0.9954,0.99534,0.9954,0.99534,52

specific code is `con.get_candles('USD/CHF', period = 'm1', number = 1440 )`

but always lose data, for instance below, this is USD/CHF m1 period data, 

data row `2018-08-07 23:51:00` has gone, it's lost, why have this problem, 

is this caused by network or original data problem? or whatever problem?

i'm believe this lost not only one, because i'm try to merge six currencies, merge data have lots of row is empty, some time is one currencies, some time is another one, 

can you fix it ? or tell me why have this problem and how to solve it, 

thanks

**Comment by FXCMAPI** [comment]
Can you tell us the name of the middleware sotftware that you are using so we can investigate it ?

As for the candle issue - there were no ticks for USD/CHF 2018-08-07 23:50:00.
If you look at values returned, ask open and bid open for 2018-08-07 23:51:00 are the same as ask close and bid close for 2018-08-07 23:49:00

Best Regards,
Pawel

**Comment by henryatman** [comment]
@FXCMAPI 

hi, i'm back... with some time problem, for example (EURUSD):

in MT4 platform, week end at "2018.08.10 23:54", 
in FXCMPY api, week end at "2018-08-10 20:59",

even have different time Offset, why not time offset isn't full hour offset，like all is 
2018.08.10 23:59
2018-08-10 20:59

Is there have any problem with MT4? 
like MT4 lost last 5 minute data or MT4 stop market trade early than FXCM（5 minute ）？

what exactly key problem is ? how to corresponding two different time offset？

i'm want to know how calculate MT4 and FXCM time offset, and above problem,

please help me know, thanks

---
capture picture

![image](https://user-images.githubusercontent.com/5210789/44000355-0723ea2a-9e51-11e8-9f3e-cd1f43c9e85d.png)



![image](https://user-images.githubusercontent.com/5210789/44000379-65479aca-9e51-11e8-8381-b94fa50762aa.png)

**Comment by FXCMAPI** [comment]
Hello 王弘毅

Our system stopped at 20:55 UTC,
In API, Prices may still be updating till 21:00 UTC, but clients can no longer trade.
In MT4, it has a schedule been set to close the market at 20:55, and so no trading is possible and no prices are stored in the charts after market is closed

Hope this help

Best regards
Lei
