### ISSUE TITLE
Possible to get latest price without subscribing to market?

### ISSUE THREAD

**Issue by JTInfinite** [fxcm/fxcmpy#14]
Is it possible to get a single price from a market ~~with~~ without subscribing? i.e. I want to get the latest price of GBP/USD in a single function call? It will help me when converting pip value to my account currency so I can properly manage risk.

**Comment by FXCMAPI** [comment]
Hello Joe

Yes, you can use get_last_price after you subscribe

Best regards
Lei

**Comment by JTInfinite** [comment]
Can't believe I wrote 'with subscribing'. I meant without subscribing.

Thanks for the swift response

**Comment by FXCMAPI** [comment]
Hi,

To use the get_last_price() function you need to subscribe first, for example:
con.subscribe_market_data('EUR/USD')


Regards,
Daniel Halpert

**Comment by FXCMAPI** [comment]
if you don't want to subscribe, you can request snapshot of offer table. 
it contains last bid/offer, 
Be aware that you need to enable the currencies on TSweb 2.0.
closing it
