### ISSUE TITLE
No price stream for <pair>

### ISSUE THREAD

**Issue by Amarchuk** [fxcm/fxcmpy#6]
Hi,

I encountered a strange error today - the next code snippet 
```python
import fxcmpy
con = fxcmpy.fxcmpy(access_token=TOKEN, log_level='error')
con.subscribe_market_data('GBP/USD')
```
produce 
```bash
File "/usr/local/lib/python3.5/dist-packages/fxcmpy/fxcmpy.py", line 666, in subscribe_market_data
    protocol='post')
  File "/usr/local/lib/python3.5/dist-packages/fxcmpy/fxcmpy.py", line 2215, in __handle_request__
    % data['response']['error'])
fxcmpy.fxcmpy.ServerError: FXCM Server reports an error: No price stream for GBP/USD.
```

I try several instrument pairs (with the same result), subscribe/unsubscribe in GUI, but nothing works.

**Comment by schwed2** [comment]
Tried to reproduce the error but everything runs fine. It seems that has been a temporary problem with the backend. Just to be sure, could you please test it again?

Best
Michael

**Comment by Amarchuk** [comment]
@schwed2 Yes, its gone now. I also thinks it was temporary, thanks.
