### ISSUE TITLE
get_open_positions is not updated before connection closed

### ISSUE THREAD

**Issue by Amarchuk** [fxcm/fxcmpy#7]
Hi,

I notice that get_open_positions() method works really strange. For example, I have two open positions.
Using next code snippet:
```bash
import fxcmpy
import time
con = fxcmpy.fxcmpy(access_token=TOKEN, log_level='error')
print(con.get_open_positions().T) #ATTEMPT 1 
time.sleep(120)
print(con.get_open_positions().T) #ATTEMPT 2 
con.close()
con = fxcmpy.fxcmpy(access_token=TOKEN, log_level='error')
print(con.get_open_positions().T) #ATTEMPT 3 
```
the results from attempts 1 & 2 are always the same (and not depends from sleep time). 

Obviously, at least `visiblePL` and `close` should changes (as they do in Trading Station GUI). If you will interrupt the connection and then restore it again - the returned data in attempt 3 changes.

What do you think? Is this a bug?

Thanks!

**Comment by schwed2** [comment]
For me, th update works fine:
`print(con.get_open_positions().T) #ATTEMPT 1 
time.sleep(120)
print(con.get_open_positions().T) #ATTEMPT 2 `  

gives 

`                            0
accountId             2815291
accountName       02815291
amountK              50
close                     110.919
com                      0
currency               USD/JPY
currencyPoint       4.50737
grossPL                414.266
isBuy                    True
isDisabled             False
limit                     112
open                    110
ratePrecision        3
roll                      49.96
stop                     0
stopMove            0
t                          1
time                     06072018140332
tradeId                 178168201
usedMargin          500
valueDate                    
visiblePL                **91.9**

                            0
accountId             2815291
accountName       02815291
amountK              50
close                     110.913
com                      0
currency                USD/JPY
currencyPoint        4.50761
grossPL                 411.584
isBuy                     True
isDisabled              False
limit                      112
open                     110
ratePrecision          3
roll                        49.96
stop                      0
stopMove             0
t                           1
time                     06072018140332
tradeId                178168201
usedMargin         500
valueDate                    
visiblePL               **91.3**`

**Comment by Amarchuk** [comment]
Again, I am not sure what the actual reason of this behaviour was.  Now everything works.

Thanks
