### ISSUE TITLE
Invalid settings of parameneters.

### ISSUE THREAD

**Issue by gcavelier** [fxcm/fxcmpy#8]
Hi,

I get the following error when calling get_candles() : 

|ERROR|2018-07-04 13:27:18,415|Server reports an error: {'executed': False, 'error': 'Invalid settings of parameneters.'}.
Traceback (most recent call last):
  File "test.py", line 52, in <module>
    data = fxcm.get_candles('EUR/USD', period='M1', number=1, start='2017-01-01')
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/fxcmpy/fxcmpy.py", line 2068, in get_candles
    % (offer_id, period), params=params)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/fxcmpy/fxcmpy.py", line 2336, in __handle_request__
    % data['response']['error'])
fxcmpy.fxcmpy.ServerError: FXCM Server reports an error: Invalid settings of parameneters..

Am I doing something wrong ?

Thanks

**Comment by FXCMAPI** [comment]
Hi,

There are two ways to call get_candles,  for example:

1.  con.get_candles('EUR/USD', period='m1', number=5)

2.  con.get_candles('EUR/USD', period='D1', start=start, end=end)
so start parameter should be used with end parameter, if using number parameter then don’t included start nor end.

Regards,
Daniel Halpert

**Comment by gcavelier** [comment]
ok, I didn't know about that.

It's working fine when using "start=" *and* "end="

Thank you!
